name: CI

on: ['push', 'pull_request']

env:
  PRIVATE_REPO: "${{ github.workspace }}/build/githubActionGrettyPrivateRepository"

jobs:

  build:
    name: Build Gretty
    runs-on: ubuntu-latest

    env:
      JDK_VERSION: "11"
      GRADLE_VERSION: "6.9.2"

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK ${{ env.JDK_VERSION }}
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ env.JDK_VERSION }}

      - name: Build with Gradle ${{ env.GRADLE_VERSION }}
        run: |
          set -e
          ./gradlew --no-daemon wrapper --gradle-version $GRADLE_VERSION --distribution-type all
          ./gradlew --no-daemon --warning-mode all -PprivateRepoDir=$PRIVATE_REPO build
          set +e

      - uses: actions/upload-artifact@v3
        with:
          name: gretty-private-repository
          path: ${{ env.PRIVATE_REPO }}

  test:
    name: Gradle ${{ matrix.gradle }} on Java ${{ matrix.java }}
    runs-on: ubuntu-latest
    needs: build

    strategy:
      matrix:
        include:

          - java: 11
            gradle: '6.9.4'

          - java: 11
            gradle: '7.6.2'
            properties: '-Pspock_version=2.0-groovy-3.0 -PgebVersion=5.0'

          - java: 17
            gradle: '7.6.2'
            properties: '-Pspock_version=2.0-groovy-3.0 -PgebVersion=5.0'

          - java: 17
            gradle: '8.2.1'
            properties: '-Pspock_version=2.0-groovy-3.0 -PgebVersion=5.0'

    env:
      TEST_ALL_CONTAINERS: ${{ matrix.container }}
      GRADLE_VERSION: ${{ matrix.gradle }}
      EXTRA_PROPERTIES: ${{ matrix.properties }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: gretty-private-repository
          path: ${{ env.PRIVATE_REPO }}

      # Begin workaround: because the current Gradle wrapper does not support Java 17,
      # we use JDK 15 to bootstrap the appropriate Gradle version, and then proceed
      # to use a recent version of Gradle and Java.
      - name: Set up JDK 15
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 15
      - name: Bootstrap Gradle version
        run: ./gradlew --no-daemon wrapper --gradle-version $GRADLE_VERSION --distribution-type all
      # end workaround

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}

      - name: Set up Gradle ${{ matrix.gradle }}
        run: ./gradlew --no-daemon wrapper --gradle-version $GRADLE_VERSION --distribution-type all

      # begin workaround - see also integrationTests/buildSrc/build.gradle
      - name: Install buildSrc project (only required for Gradle 8)
        run: |
          ../../gradlew --no-daemon \
            --warning-mode all \
            -PprivateRepoDir=$PRIVATE_REPO \
            publishToPrivateRepo
        if: "startsWith(env.GRADLE_VERSION, '8.')"
        working-directory: integrationTests/buildSrc
      # end workaround

      - name: Run Integration Tests
        run: |
          ../gradlew --no-daemon \
            --warning-mode all \
            -PprivateRepoDir=$PRIVATE_REPO \
            $EXTRA_PROPERTIES \
            -PgeckoDriverPlatform=linux64 \
            -PtestAllContainers=$TEST_ALL_CONTAINERS \
            testAll
        working-directory: integrationTests
